name: Lint codebase and commit changes

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2

    - run: pip install ruff

    - run: ruff format .

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'ruff'
        file_pattern: '*.py'


